[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
konahrik = "3AhgyMSPhsKQFevVwGF2XNcDs8wBDxjz7g1HotFNNPWp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
